[package]
name = "SillyDelay"
version = "0.1.0"
authors = ["volfym <volfym@volfym.space>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vst = "0.1.0"
queues = "1.0.2"

[lib]
crate-type = ["dylib"]